### ISSUE TITLE
Lack of transition violates material design principles

### ISSUE THREAD

**Issue by cayblood** [Polymer/core-tooltip#10]
core-tooltip should have some kind of transition when it appears, such as a fade-in or expand.

**Comment by kbwatts** [comment]
:+1: 

Using css .fancy class similar to https://www.polymer-project.org/components/core-tooltip/demo.html for now, but might be in line with material design spec to build this in by default or at least as an attribute.

**Comment by ebidel** [comment]
FWIW, this is a generic tooltip element. What we really need is to build a paper-tooltip with MD's design :)

**Comment by kbwatts** [comment]
Good point - easy to forget when even the core-* elements look so good :)

+1 for paper-tooltip
