### ISSUE TITLE
Consider "title" instead of "label"

### ISSUE THREAD

**Issue by ssorallen** [Polymer/core-tooltip#25]
Tooltips are improvements on the native functionality of the "title" attribute, i.e. show a message on a long enough hover (on a platform with a pointer). Using native/standard "title" instead of the custom "label" gives fallback functionality and keeps the API familiar to someone who knows HTML.

**Comment by ebidel** [comment]
The problem with the native `title` is that it's not observable by the data binding system. e.g. `titleChanged` is never called, etc. I'd love to use `title`, but it's not really possible :( We could duplicate `label` to the `title` attr. WDYT?

**Comment by ssorallen** [comment]
I proposed this because "label" is an odd overloading of the term given `<label>` is an HTML element. Maybe another version of "title" like "tooltipTitle" would do it and set the native "title" as well.
