### ISSUE TITLE
Where's 1.0 version for this element?

### ISSUE THREAD

**Issue by Mygod** [Polymer/core-tooltip#35]
There's neither `iron-tooltip` nor `paper-tooltip`. Does this mean I should probably go back to using `title` attribute? :cry:

**Comment by ebidel** [comment]
This one was low priority for the initial release, but we'll definitely get something out in the coming weeks.

**Comment by eximius313** [comment]
+1

**Comment by Pickachu** [comment]
:+1:

**Comment by jhou-pro** [comment]
+1

**Comment by exload** [comment]
+1

**Comment by sansantosh** [comment]
+1

**Comment by pshihn** [comment]
+1

**Comment by luccamordente** [comment]
+1

**Comment by ValueBC** [comment]
+1

**Comment by shkate** [comment]
+1

**Comment by kiryaka** [comment]
+1

**Comment by avm99963** [comment]
+1

**Comment by M0nter0** [comment]
The element is "in progress" as you can see in the road-map for paper elements.
https://github.com/PolymerElements/paper-elements

**Comment by notwaldorf** [comment]
Closing this, as it's technically a duplicate of https://github.com/PolymerElements/paper-elements/issues/18. I have a PR out for `paper-tooltip`, and it should be ready hopefully by next week.

**Comment by Mygod** [comment]
A temporary workaround for people who are immigrating from 0.5:

    <dom-module id="paper-tooltip">
        <script>
            Polymer({
                is: "paper-tooltip",
                ready: function () {
                    var tip = this.querySelector("[tip]");
                    this.setAttribute("title", tip.innerText);
                    tip.remove();
                }
            });
        </script>
    </dom-module>

**Comment by Sinjins** [comment]
+1

**Comment by notwaldorf** [comment]
:wave: Here it is: https://github.com/PolymerElements/paper-tooltip. 😊
